// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5f5AfgLKjazMlLYK5X_Q7LvOGHQ5_g1s',
    appId: '1:48021355614:web:f925984c9f0b4b5b4988cf',
    messagingSenderId: '48021355614',
    projectId: 'plugsharex',
    authDomain: 'plugsharex.firebaseapp.com',
    storageBucket: 'plugsharex.firebasestorage.app',
    measurementId: 'G-1E0WF8VRX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNqP-UeKV-ncro9fXpmYgnYqLrQ5v5u-g',
    appId: '1:48021355614:android:2f7beefa4adfee744988cf',
    messagingSenderId: '48021355614',
    projectId: 'plugsharex',
    storageBucket: 'plugsharex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0LjrtGNwQEyFzQWYwyKu23NI25V9el8',
    appId: '1:48021355614:ios:4608947078a186dd4988cf',
    messagingSenderId: '48021355614',
    projectId: 'plugsharex',
    storageBucket: 'plugsharex.firebasestorage.app',
    iosBundleId: 'com.example.electrahome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0LjrtGNwQEyFzQWYwyKu23NI25V9el8',
    appId: '1:48021355614:ios:4608947078a186dd4988cf',
    messagingSenderId: '48021355614',
    projectId: 'plugsharex',
    storageBucket: 'plugsharex.firebasestorage.app',
    iosBundleId: 'com.example.electrahome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5f5AfgLKjazMlLYK5X_Q7LvOGHQ5_g1s',
    appId: '1:48021355614:web:fe67fc31d7a3a3494988cf',
    messagingSenderId: '48021355614',
    projectId: 'plugsharex',
    authDomain: 'plugsharex.firebaseapp.com',
    storageBucket: 'plugsharex.firebasestorage.app',
    measurementId: 'G-31F6BBD4SC',
  );

}